"""
Layer 3, arm C -- STRUCTURED-FIRST HYBRID.

Arm A (fixed RAG)   overall 0.223, aggregate 0.011
Arm B (router)      overall 0.429, aggregate 0.690, lookup unchanged at 0.315

Arm B fixed aggregation but left lookup on dense retrieval, where the gold
receipt reached the top-5 only 34% of the time. That is a weak retrieval
baseline, not a property of the task: vendor names and dates are exact strings,
and the intent extractor already recovers them before retrieval runs. Embedding
"receipt from MEI LET RESTAURANT on 12 March 2017" and hoping cosine similarity
finds the right receipt discards information the system already holds.

This arm resolves the document through the structured store first --
vendor + date, or vendor + amount -- and falls back to dense retrieval only
when that fails. The answer is still generated by the LLM from the retrieved
receipt TEXT, so this measures retrieval quality, not a direct field read.

Every record also carries `db_answer`: what the structured field says outright.
That is the ceiling Layer-1 extraction imposes on this pipeline, and reporting
the two together separates retrieval error from extraction error.

CAVEAT for the write-up: the questions were generated from gold fields, so
vendor+date is a well-formed handle by construction. A real SME question may be
vaguer ("that hardware shop last month"). This arm should be presented as an
upper bound on structured resolution, with the dense-retrieval arm as the lower
bound for unstructured phrasing.

    python layer3/run_hybrid.py --limit 10
    python layer3/run_hybrid.py

Writes layer3/runs/hybrid__whole__k5.jsonl
"""
import argparse
import json
import math
import os
import re
import time
from pathlib import Path

import psycopg
import torch

DSN = os.environ.get("DOCAI_DSN", "postgresql:///docai")
ROOT = Path(__file__).resolve().parents[1]
QA = ROOT / "layer3" / "qa" / "sroie_qa.jsonl"
RUNS = ROOT / "layer3" / "runs"

MODEL_ID = "Qwen/Qwen2.5-VL-7B-Instruct"
EMBED_MODEL = "sentence-transformers/all-MiniLM-L6-v2"
DATASET, ARM = "sroie", "zeroshot"

INTENT_SYSTEM = """You convert a question about receipts into a JSON intent.

Reply with ONLY a JSON object, no other text. Fields:
  "action": one of
      "sum_vendor"    total spend at one vendor
      "count_vendor"  how many receipts from one vendor
      "max_vendor"    largest single purchase at one vendor
      "sum_year"      total spend in a year
      "count_year"    how many receipts in a year
      "lookup"        anything about ONE specific receipt
  "vendor": company name if named, else null
  "year": four-digit year if named, else null
  "date": the full date in YYYY-MM-DD if the question gives a full date, else null
  "amount": the money amount if the question gives one, else null
  "want": for lookup only, which field is asked for:
          "total" | "date" | "address" | "vendor" | null

Examples:
Q: How much did I spend at ABC TRADING in total?
{"action":"sum_vendor","vendor":"ABC TRADING","year":null,"date":null,"amount":null,"want":null}
Q: How much was the receipt from XYZ SDN BHD on 24 June 2018?
{"action":"lookup","vendor":"XYZ SDN BHD","year":2018,"date":"2018-06-24","amount":null,"want":"total"}
Q: When was the ACME receipt for 6.20 issued?
{"action":"lookup","vendor":"ACME","year":null,"date":null,"amount":6.20,"want":"date"}
Q: What is the address on the FOO BAR receipt from 3 May 2018?
{"action":"lookup","vendor":"FOO BAR","year":2018,"date":"2018-05-03","amount":null,"want":"address"}"""

ANSWER_SYSTEM = (
    "You answer questions about receipts using ONLY the receipt text provided. "
    "Give the shortest possible answer: a number, a date, or an address. "
    "Do not explain, do not show working, do not add currency symbols. "
    "If the answer is not present in the provided receipts, reply exactly: NOT_FOUND"
)

SQL_ACTIONS = {"sum_vendor", "count_vendor", "max_vendor", "sum_year", "count_year"}
STOP = {"sdn", "bhd", "co", "ltd", "the", "and", "m", "s", "b", "enterprise"}


# ------------------------------------------------------------------ helpers

def norm_vendor(s):
    return re.sub(r"[^a-z0-9 ]", " ", str(s or "").lower())


def tokens(s):
    return {t for t in norm_vendor(s).split() if t and t not in STOP}


class VendorIndex:
    """IDF-weighted vendor matching.

    Generic tokens (hardware, cash, carry, restoran) recur across many vendors
    and must not drive a match; rare tokens (unihakka, kuchai) must. A flat
    containment rule merged distinct companies sharing only generic words.
    """

    def __init__(self, known):
        self.known = known
        self.df = {}
        for v in known:
            for t in tokens(v):
                self.df[t] = self.df.get(t, 0) + 1
        self.n = max(len(known), 1)

    def idf(self, t):
        return math.log(self.n / (1 + self.df.get(t, 0))) + 1.0

    def match(self, name):
        want = tokens(name)
        if not want:
            return []
        w_want = sum(self.idf(t) for t in want)
        if w_want <= 0:
            return []
        out = []
        for v in self.known:
            have = tokens(v)
            if not have:
                continue
            inter = sum(self.idf(t) for t in want & have)
            if (inter / w_want >= 0.75
                    and inter / sum(self.idf(t) for t in have) >= 0.75):
                out.append(v)
        return out


def parse_intent(raw):
    m = re.search(r"\{.*\}", raw or "", re.S)
    if not m:
        return None
    try:
        d = json.loads(m.group())
    except json.JSONDecodeError:
        return None
    return d if isinstance(d, dict) and "action" in d else None


# ------------------------------------------------------------------- model

def load_model():
    from transformers import AutoProcessor, BitsAndBytesConfig
    try:
        from transformers import Qwen2_5_VLForConditionalGeneration as VLModel
    except ImportError:
        from transformers import Qwen2VLForConditionalGeneration as VLModel
    bnb = BitsAndBytesConfig(load_in_4bit=True, bnb_4bit_quant_type="nf4",
                             bnb_4bit_compute_dtype=torch.bfloat16,
                             bnb_4bit_use_double_quant=True)
    proc = AutoProcessor.from_pretrained(MODEL_ID)
    model = VLModel.from_pretrained(MODEL_ID, quantization_config=bnb,
                                    device_map="auto")
    model.eval()
    return model, proc


@torch.inference_mode()
def generate(model, proc, system, user, max_new_tokens=96):
    messages = [
        {"role": "system", "content": [{"type": "text", "text": system}]},
        {"role": "user", "content": [{"type": "text", "text": user}]},
    ]
    text = proc.apply_chat_template(messages, tokenize=False,
                                    add_generation_prompt=True)
    inputs = proc(text=[text], return_tensors="pt").to(model.device)
    t0 = time.time()
    out = model.generate(**inputs, max_new_tokens=max_new_tokens, do_sample=False)
    ms = (time.time() - t0) * 1000
    gen = out[0][inputs["input_ids"].shape[1]:]
    return proc.tokenizer.decode(gen, skip_special_tokens=True).strip(), ms


# --------------------------------------------------------------- sql paths

def sql_aggregate(cur, intent, vidx):
    action, vq, year = intent.get("action"), intent.get("vendor"), intent.get("year")
    if action in ("sum_vendor", "count_vendor", "max_vendor"):
        vendors = vidx.match(vq)
        if not vendors:
            return None, f"vendor not resolved: {vq!r}"
        agg = {"sum_vendor": "sum(total)", "count_vendor": "count(*)",
               "max_vendor": "max(total)"}[action]
        cur.execute(f"SELECT {agg} FROM documents WHERE dataset=%s AND arm=%s "
                    f"AND vendor = ANY(%s)", (DATASET, ARM, vendors))
        return cur.fetchone()[0], None
    if action in ("sum_year", "count_year"):
        if not year:
            return None, "no year"
        agg = "sum(total)" if action == "sum_year" else "count(*)"
        cur.execute(f"SELECT {agg} FROM documents WHERE dataset=%s AND arm=%s "
                    f"AND extract(year from doc_date)=%s",
                    (DATASET, ARM, int(year)))
        return cur.fetchone()[0], None
    return None, f"unroutable: {action}"


def resolve_docs(cur, intent, vidx):
    """Find the specific receipt through the structured store.

    Returns (doc_ids, how). `how` records which handle worked, so the write-up
    can report how often each resolution route fires rather than reporting a
    single opaque success rate.
    """
    vendors = vidx.match(intent.get("vendor")) if intent.get("vendor") else []
    date, amount = intent.get("date"), intent.get("amount")

    if vendors and date:
        cur.execute("SELECT doc_id FROM documents WHERE dataset=%s AND arm=%s "
                    "AND vendor = ANY(%s) AND doc_date = %s",
                    (DATASET, ARM, vendors, date))
        rows = [r[0] for r in cur.fetchall()]
        if rows:
            return rows, "vendor+date"

    if vendors and amount is not None:
        try:
            amt = float(amount)
            cur.execute("SELECT doc_id FROM documents WHERE dataset=%s AND arm=%s "
                        "AND vendor = ANY(%s) AND abs(total - %s) <= 0.01",
                        (DATASET, ARM, vendors, amt))
            rows = [r[0] for r in cur.fetchall()]
            if rows:
                return rows, "vendor+amount"
        except (TypeError, ValueError):
            pass

    if vendors:
        cur.execute("SELECT doc_id FROM documents WHERE dataset=%s AND arm=%s "
                    "AND vendor = ANY(%s) LIMIT 5", (DATASET, ARM, vendors))
        rows = [r[0] for r in cur.fetchall()]
        if rows:
            return rows, "vendor only"

    return [], "unresolved"


def db_field(cur, doc_ids, want):
    """What the structured field says outright -- the extraction ceiling."""
    col = {"total": "total", "date": "doc_date", "address": "address",
           "vendor": "vendor"}.get(want)
    if not col or not doc_ids:
        return None
    cur.execute(f"SELECT {col} FROM documents WHERE dataset=%s AND arm=%s "
                f"AND doc_id = ANY(%s) LIMIT 1", (DATASET, ARM, doc_ids))
    r = cur.fetchone()
    if not r or r[0] is None:
        return None
    v = r[0]
    if col == "total":
        return f"{float(v):.2f}"
    if col == "doc_date":
        return v.strftime("%d/%m/%Y")
    return str(v)


def fetch_text(cur, doc_ids):
    cur.execute("SELECT doc_id, text FROM chunks WHERE dataset=%s "
                "AND strategy='whole' AND doc_id = ANY(%s)", (DATASET, doc_ids))
    return cur.fetchall()


def vector_search(cur, qvec, k, table="chunks"):
    cur.execute(f"SELECT doc_id, text, 1 - (embedding <=> %s::vector) FROM {table} "
                f"WHERE dataset=%s AND strategy='whole' "
                f"ORDER BY embedding <=> %s::vector LIMIT %s",
                (qvec, DATASET, qvec, k))
    return cur.fetchall()


def numbers_in(s):
    return set(re.findall(r"\d+(?:\.\d+)?", (s or "").replace(",", "")))


def grounded(answer, context):
    if not answer or answer.strip() == "NOT_FOUND":
        return None
    nums = numbers_in(answer)
    if nums:
        return nums.issubset(numbers_in(context))
    a = re.sub(r"[^a-z0-9]", "", answer.lower())
    c = re.sub(r"[^a-z0-9]", "", context.lower())
    return bool(a) and a in c


def fmt(val, action):
    if val is None:
        return "NOT_FOUND"
    if action in ("count_vendor", "count_year"):
        return str(int(val))
    return f"{float(val):.2f}"


# --------------------------------------------------------------------- main

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--k", type=int, default=5)
    ap.add_argument("--embed", choices=["minilm","titan"], default="minilm")
    ap.add_argument("--limit", type=int, default=0)
    a = ap.parse_args()

    questions = [json.loads(l) for l in QA.open() if l.strip()]
    if a.limit:
        questions = questions[: a.limit]
    print(f"{len(questions)} questions, structured-first hybrid, k={a.k}")

    table = "chunks_titan" if a.embed == "titan" else "chunks"
    if a.embed == "titan":
        import boto3
        bd = boto3.client("bedrock-runtime", region_name="eu-west-1")
        def encode(t):
            r = bd.invoke_model(modelId="amazon.titan-embed-text-v2:0",
                body=json.dumps({"inputText": t[:8000], "dimensions": 1024,
                                 "normalize": True}))
            return json.loads(r["body"].read())["embedding"]
    else:
        from sentence_transformers import SentenceTransformer
        _m = SentenceTransformer(EMBED_MODEL, device="cuda")
        encode = lambda t: list(map(float, _m.encode(t, normalize_embeddings=True)))

    print(f"loading {MODEL_ID} in 4-bit...")
    model, proc = load_model()

    RUNS.mkdir(parents=True, exist_ok=True)
    out_path = RUNS / f"hybrid_{a.embed}__whole__k{a.k}.jsonl"

    with psycopg.connect(DSN) as conn, conn.cursor() as cur, out_path.open("w") as fh:
        cur.execute("SELECT DISTINCT vendor FROM documents WHERE dataset=%s "
                    "AND arm=%s AND vendor IS NOT NULL", (DATASET, ARM))
        vidx = VendorIndex([r[0] for r in cur.fetchall()])
        print(f"{len(vidx.known)} distinct vendors indexed")

        for i, q in enumerate(questions, 1):
            raw, ms_intent = generate(model, proc, INTENT_SYSTEM,
                                      q["question"], max_new_tokens=110)
            intent = parse_intent(raw) or {"action": "lookup"}
            action = intent.get("action", "lookup")

            rec = {"qid": q["qid"], "kind": q["kind"], "field": q["field"],
                   "question": q["question"], "gold_answer": q["gold_answer"],
                   "gold_docs": q["gold_docs"], "model": MODEL_ID,
                   "strategy": "whole", "k": a.k, "intent": intent,
                   "intent_raw": raw[:200],
                   "route_correct": (action in SQL_ACTIONS) == (q["kind"] == "aggregate"),
                   "cost_usd": 0.0}

            if action in SQL_ACTIONS:
                try:
                    val, err = sql_aggregate(cur, intent, vidx)
                except Exception as exc:                     # noqa: BLE001
                    conn.rollback()
                    val, err = None, str(exc)[:200]
                rec.update({"route": "sql", "resolution": "aggregate",
                            "model_answer": fmt(val, action), "db_answer": None,
                            "retrieved_docs": [], "similarities": [],
                            "top_similarity": None, "retrieval_hit": None,
                            "answer_grounded": None, "latency_ms": ms_intent,
                            "error": err})
            else:
                try:
                    doc_ids, how = resolve_docs(cur, intent, vidx)
                except Exception as exc:                     # noqa: BLE001
                    conn.rollback()
                    doc_ids, how = [], f"error: {str(exc)[:80]}"

                sims = []
                if doc_ids:
                    rows = fetch_text(cur, doc_ids)
                    docs = [r[0] for r in rows]
                    context = "\n\n---\n\n".join(
                        f"[receipt {d}]\n{t}" for d, t in rows)
                    dbv = db_field(cur, doc_ids, intent.get("want"))
                else:
                    qv = str(encode(q["question"]))
                    rows = vector_search(cur, qv, a.k, table)
                    docs = [r[0] for r in rows]
                    sims = [round(float(r[2]), 4) for r in rows]
                    context = "\n\n---\n\n".join(
                        f"[receipt {d}]\n{t}" for d, t, _ in rows)
                    dbv = None
                    how = "vector fallback"

                try:
                    ans, ms_ans = generate(
                        model, proc, ANSWER_SYSTEM,
                        f"Receipts:\n\n{context}\n\nQuestion: {q['question']}",
                        max_new_tokens=64)
                    err = None
                except Exception as exc:                     # noqa: BLE001
                    ans, ms_ans, err = None, 0, str(exc)[:200]

                rec.update({"route": "structured" if doc_ids else "vector",
                            "resolution": how, "model_answer": ans,
                            "db_answer": dbv, "retrieved_docs": docs,
                            "similarities": sims,
                            "top_similarity": sims[0] if sims else None,
                            "retrieval_hit": bool(set(docs) & set(q["gold_docs"])),
                            "answer_grounded": grounded(ans, context),
                            "latency_ms": ms_intent + ms_ans, "error": err})

            fh.write(json.dumps(rec) + "\n")
            if i % 25 == 0 or i == len(questions):
                print(f"  {i}/{len(questions)}")

    print(f"\nwrote {out_path}")


if __name__ == "__main__":
    main()
